import { Inter } from "next/font/google";
import "./globals.css";
import bgGrid from "../../public/redwalletgrid.svg";
const inter = Inter({ subsets: ["latin"] });
import VariableState from "./provider/VariablesState";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Red Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            backgroundImage: `url(${bgGrid.src})`,
            backgroundSize: "40%", // Resize the image to 150% of its original size
            backgroundRepeat: "repeat",
            backgroundColor: "#181818",
            // height: "100vh",
            height: "100%",
          }}
          className=""
        >
          <VariableState>{children}</VariableState>
          <Toaster position="top-right" toastOptions={{ duration: 3000 }} />
        </div>
      </body>
    </html>
  );
}
